In [ ]:
import torch

## 2.1 Создание нейронов и полносвязных слоев

2.1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат. 

In [ ]:
class Neuron:
  def __init__(self, weights, bias):
    # <создать атрибуты объекта weights и bias>
    
    self.weights = weights
    self.bias = bias
  
  def forward(self, inputs):
    return inputs @ self.weights.T + self.bias # <реализовать логику нейрона>
    # return torch.matmul(inputs, self.weights) + self.bias # <реализовать логику нейрона>

In [ ]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14

Neuron(weights, bias).forward(inputs)

tensor(4.8400)

In [ ]:
torch.nn.functional.linear(inputs, weights, torch.tensor(bias))

tensor(4.8400)

2.1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат. 

In [ ]:
class Linear:
  def __init__(self, weights, biases):
    # <создать атрибуты объекта weights и biases>
    self.weights = weights
    self.biases = biases
    pass
  
  def forward(self, inputs):
    return inputs @ self.weights.T + self.biases # <реализовать логику слоя>
    # return torch.matmul(inputs, self.weights) + self.biases # <реализовать логику слоя>

In [ ]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]])

biases = torch.tensor([3.14, 2.71, 7.2])

Linear(weights, biases).forward(inputs)

tensor([ 4.8400,  0.1700, 10.3900])

In [ ]:
torch.nn.functional.linear(inputs, weights, biases)

tensor([ 4.8400,  0.1700, 10.3900])

2.1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

Linear(weights, biases).forward(inputs)

tensor([[ 3.7900,  0.9200,  9.0850],
        [ 6.1400, -2.1000,  6.9000],
        [ 2.0400,  0.7610,  6.7260]])

In [ ]:
torch.nn.functional.linear(inputs, weights, biases)

tensor([[ 3.7900,  0.9200,  9.0850],
        [ 6.1400, -2.1000,  6.9000],
        [ 2.0400,  0.7610,  6.7260]])

2.1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [ ]:
class Linear:
  def __init__(self, n_features, n_neurons):
    # <создать атрибуты объекта weights и biases>
    self.weights = torch.nn.parameter.Parameter(torch.normal(0, 1, (n_neurons, n_features)))
    self.biases = torch.nn.parameter.Parameter(torch.normal(0, 1, (n_neurons, )))
  
  def forward(self, inputs):
    return inputs @ self.weights.T + self.biases # <реализовать логику слоя>
    # return torch.matmul(inputs, self.weights) + self.biases # <реализовать логику слоя>

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

Linear(inputs.shape[1], 2).forward(inputs)

tensor([[-4.5832, -4.1243],
        [-1.2777, -3.2878],
        [-4.7655, -5.1394]], grad_fn=<AddBackward0>)

2.1.5 Используя решение из __2.1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7). 

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

In [ ]:
x = Linear(inputs.shape[1], 14).forward(inputs)
x = Linear(14, 7).forward(x)
x

tensor([[ 16.8782,  -9.1170,  19.7635,   7.7159,  -9.9444,  17.5729, -13.2913],
        [ 10.2420, -15.1346,  -0.1252,  21.3473,  -0.4931,   4.8868, -11.4041],
        [ 28.3574,  -1.4950,  30.2217,  17.9461, -14.2223,  -3.5170, -14.1812]],
       grad_fn=<AddBackward0>)

## 2.2 Создание функций активации

2.2.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [ ]:
class ReLU:
  def forward(self, inputs):
    # <реализовать логику ReLU>
    return torch.maximum(torch.tensor(0), inputs)

In [ ]:
inputs = torch.tensor([-2., -1., 0., 1., 2.])

ReLU().forward(inputs)

tensor([0., 0., 0., 1., 2.])

In [ ]:
torch.relu(inputs)

tensor([0., 0., 0., 1., 2.])

2.2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров.

In [ ]:
class Softmax:
  def forward(self, inputs):
    # <реализовать логику Softmax>
    e = torch.exp(inputs)
    e_sum = torch.sum(e, 1).reshape(-1, 1)
    return e / e_sum

In [ ]:
inputs = torch.normal(2, 1, (4, 3))
inputs

tensor([[2.2970, 1.4620, 1.3028],
        [2.8524, 4.3715, 2.5754],
        [0.0876, 2.4208, 1.1439],
        [3.0184, 2.9507, 0.1744]])

In [ ]:
Softmax().forward(inputs)

tensor([[0.5544, 0.2405, 0.2051],
        [0.1581, 0.7221, 0.1198],
        [0.0705, 0.7268, 0.2027],
        [0.5018, 0.4690, 0.0292]])

In [ ]:
torch.softmax(inputs, 1)

tensor([[0.5544, 0.2405, 0.2051],
        [0.1581, 0.7221, 0.1198],
        [0.0705, 0.7268, 0.2027],
        [0.5018, 0.4690, 0.0292]])

2.2.3 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [ ]:
class ELU:
  def __init__(self, alpha):
    # <создать атрибут объекта alpha>
    self.alpha = alpha

  def forward(self, inputs):
    # <реализовать логику ELU>
    return torch.where(inputs > 0, inputs, self.alpha * (torch.exp(inputs) - 1))

In [ ]:
inputs = torch.tensor([-2., -1., 0., 1., 2.])

ELU(1).forward(inputs)

tensor([-0.8647, -0.6321,  0.0000,  1.0000,  2.0000])

In [ ]:
torch._C._nn.elu(inputs)

tensor([-0.8647, -0.6321,  0.0000,  1.0000,  2.0000])

## 2.3 Создание функции потерь

2.3.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)

Создать полносвязный слой с 1 нейроном, прогнать через него батч `inputs` и посчитать значение MSE, трактуя вектор `y` как вектор правильных ответов.

In [ ]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return torch.mean(torch.pow(y_true - y_pred, 2)) # <реализовать логику MSE>

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([2, 3, 4])

In [ ]:
x = Linear(inputs.shape[1], 1).forward(inputs)

MSELoss().forward(x, y.reshape(-1, 1))

tensor(23.4316, grad_fn=<MeanBackward0>)

In [ ]:
torch.nn.functional.mse_loss(x, y.reshape(-1, 1), reduction="mean")

tensor(23.4316, grad_fn=<MseLossBackward0>)

2.3.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь Categorical Cross-Entropy:

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

Создать полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустить через функцию активации softmax. Посчитать значение CCE, трактуя вектор `y` как вектор правильных ответов.

In [ ]:
class CategoricalCrossentropyLoss:
  def forward(self, y_pred, y_true):
    # <реализовать логику CCE>
    eps = torch.finfo(float).eps
    y_pred = torch.clip(y_pred, eps, 1. - eps)
    return -torch.sum(y_true * torch.log(y_pred + eps)) / y_pred.shape[0]

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                        [2, 5, -1, 2], 
                        [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([1, 0, 0])

In [ ]:
x = Linear(inputs.shape[1], 3).forward(inputs)
x = Softmax().forward(x)

CategoricalCrossentropyLoss().forward(x, torch.nn.functional.one_hot(y, 3))

tensor(3.6965, grad_fn=<DivBackward0>)

In [ ]:
torch.nn.NLLLoss()(torch.log(x), y)

tensor(3.6965, grad_fn=<NllLossBackward0>)

2.3.3 Модифицировать 2.3.1, добавив L2-регуляризацию.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/d92ca2429275bfdc0474523babbafe014ca8b580)


In [ ]:
class MSELossL2:
  def __init__(self, lambda_):
    # <создать атрибут объекта lambda_>
    self.lambda_ = lambda_

  def data_loss(self, y_pred, y_true):
    # <подсчет первого слагаемого из формулы>
    return torch.mean(torch.pow(y_true - y_pred, 2))

  def reg_loss(self, layer):
    # используйте атрибуты объекта layer, в которых хранятся веса слоя
    # <подсчет второго слагаемого из формулы>
    return self.lambda_ * torch.sum(torch.pow(layer.weights, 2))

  def forward(self, y_pred, y_true, layer):
    return self.data_loss(y_pred, y_true) + self.reg_loss(layer)

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([2, 3, 4])

In [ ]:
layer = Linear(inputs.shape[1], 1)
x = layer.forward(inputs)

MSELossL2(1).forward(x, y.reshape(-1, 1), layer)

tensor(83.8690, grad_fn=<AddBackward0>)

## 2.4 Обратное распространение ошибки

2.4.1 Используя один нейрон и SGD (1 пример за шаг), решите задачу регрессии

In [ ]:
from sklearn.datasets import make_regression

X, y, coef = make_regression(n_samples=10000, n_features=4, n_informative=4, coef=True, bias=0.5)
X = torch.tensor(X).type(torch.float32) # <преобразуйте массивы numpy в тензоры torch с типом torch.float32
y = torch.tensor(y).type(torch.float32) # <преобразуйте массивы numpy в тензоры torch с типом torch.float32

In [ ]:
import itertools

layer = torch.nn.Linear(X.shape[1], 1)
optimizer = torch.optim.SGD(layer.parameters(), lr=0.001)
dataloader = itertools.cycle(zip(X, y))

max_iters = 4000
i = 0
while i < max_iters:
  i += 1
  x, y = next(dataloader)
  optimizer.zero_grad()
  pred = layer(x)
  loss = torch.nn.functional.mse_loss(pred, y.resize(1))
  loss.backward()
  optimizer.step()
  if i % 500 == 0:
    print('iter:', i, 'loss:', loss.item())

iter: 500 loss: 1252.6329345703125
iter: 1000 loss: 397.4056396484375
iter: 1500 loss: 67.45257568359375
iter: 2000 loss: 6.735219478607178
iter: 2500 loss: 0.06698165088891983
iter: 3000 loss: 0.06477481871843338
iter: 3500 loss: 0.0016415381105616689
iter: 4000 loss: 0.0005014138878323138


[Граф вычислений для этой задачи](https://i.ibb.co/2dhDxZx/photo-2021-02-15-17-18-04.jpg)

2.4.1.1 Реализуйте класс `SquaredLoss`


In [ ]:
class SquaredLoss:
  def forward(self, y_pred, y_true):
    return torch.mean(torch.pow(y_true - y_pred, 2)) # <реализовать логику MSE>

  def backward(self, y_pred, y_true):
    self.dinput = torch.mean(-2.0*(y_true - y_pred)).repeat(y_pred.shape[0])

In [ ]:
x = torch.tensor([1.0])
y = torch.tensor([3.0])

w = torch.tensor([1.0], requires_grad=True)
y_pred = x * w

loss_fn = SquaredLoss()
loss_fn.backward(y_pred, y)
loss_fn.dinput

tensor([-4.], grad_fn=<RepeatBackward0>)

In [ ]:
x = torch.tensor([1.0])
y = torch.tensor([3.0])

w = torch.tensor([1.0], requires_grad=True)
y_pred = x * w

loss_fn = SquaredLoss()
loss = loss_fn.forward(y_pred, y)
loss.backward()

w.grad

tensor([-4.])

2.4.1.2. Модифицируйте класс `Neuron` из __2.1.1__:

  1) Сделайте так, чтобы веса нейрона инициализировались из стандартного нормального распределения

  2) Реализуйте расчет градиента относительно весов `weights` и `bias`

In [ ]:
class Neuron:
  def __init__(self, n_inputs):
    # <создать атрибуты объекта weights и bias>
    self.weights = torch.nn.parameter.Parameter(torch.normal(0, 1, (n_inputs, )))
    self.bias = torch.nn.parameter.Parameter(torch.normal(0, 1, (n_inputs, )))
  
  def forward(self, inputs):
    self.inputs = inputs
    return torch.matmul(inputs, self.weights) + self.bias # <реализовать логику нейрона>
  
  def backward(self, dvalue):
    # dvalue - значение производной, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет значение df/dc (созданное методом backwards у объекта MSELoss)
    self.dweights = torch.matmul(self.inputs.T, dvalue) # df/dW
    self.dbias = torch.sum(dvalue, axis=0, keepdims=True) # df/dB
    self.dinput = torch.dot(dvalue, self.weights.T) # df/wX

In [ ]:
x = torch.tensor([1.0])
y = torch.tensor([3.0])

layer = Neuron(1)
y_pred = layer.forward(x)

In [ ]:
loss_fn = SquaredLoss()
loss_fn.backward(y_pred, y)

layer.backward(loss_fn.dinput)
layer.dweights, layer.dbias

(tensor(-4.9906, grad_fn=<DotBackward0>),
 tensor([-4.9906], grad_fn=<SumBackward1>))

In [ ]:
loss_fn = SquaredLoss()
loss = loss_fn.forward(y_pred, y)
loss.backward()

layer.weights.grad, layer.bias.grad

(tensor([-4.9906]), tensor([-4.9906]))

2.4.1.3 Допишите цикл для настройки весов нейрона

[SGD](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D1%85%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/dda3670f8a8996a0d3bf80856bb4a166cc8db6d4)

In [ ]:
from sklearn.datasets import make_regression

X, y, coef = make_regression(n_samples=10000, n_features=4, n_informative=4, coef=True, bias=0.5)
X = torch.tensor(X).type(torch.float32) # <преобразуйте массивы numpy в тензоры torch с типом torch.float32
y = torch.tensor(y).type(torch.float32) # <преобразуйте массивы numpy в тензоры torch с типом torch.float32

In [ ]:
n_inputs = X.shape[-1] # <размерность элемента выборки>
learning_rate = 0.01 # скорость обучения
n_epoch = 100 # количество эпох

layer = Neuron(n_inputs)
loss_fn = SquaredLoss()

losses = []
for epoch in range(n_epoch):
  for x, y in zip(X, y.reshape(-1, 1)):
    # forward pass
    y_pred = layer.forward(x) # <прогон через нейрон>
    loss = loss_fn.forward(y_pred, y) # <прогон через функцию потерь>
    losses.append(loss)

    # backprop
    # <вызов методов backward>
    # обратите внимание на последовательность вызовов: от конца к началу
    loss_fn.backward(y_pred, y)
    layer.backward(loss_fn.dinput)

    # <шаг оптимизации для весов (weights и bias) нейрона>
    layer.weights = layer.weights - learning_rate * layer.dweights
    layer.bias = layer.bias - learning_rate * layer.dbias
  if epoch % 10 == 0:
    print('epoch:', epoch, 'loss:', loss.item())

epoch: 0 loss: 2008.5240478515625
epoch: 10 loss: 545.2872314453125
epoch: 20 loss: 95.52738952636719
epoch: 30 loss: 17.209354400634766
epoch: 40 loss: 3.5716164112091064
epoch: 50 loss: 1.1968295574188232
epoch: 60 loss: 0.7832964658737183
epoch: 70 loss: 0.7112857699394226
epoch: 80 loss: 0.6987461447715759
epoch: 90 loss: 0.6965627670288086


In [ ]:
torch.mean(y_pred).item(), y.item()

(-40.037567138671875, -40.037662506103516)

In [ ]:
layer.weights

tensor([-14.2596, -12.2351, -12.4232, -14.4508], grad_fn=<SubBackward0>)

In [ ]:
layer.bias

tensor([-12.5114, -12.7842, -12.7870, -14.0759], grad_fn=<SubBackward0>)

2.4.2 Решите задачу 2.4.1, используя пакетный градиентный спуск

Вычисления для этой задачи: 
[1](https://i.ibb.co/rmtQT6P/photo-2021-02-15-18-00-43.jpg)
[2](https://i.ibb.co/NmCFVnQ/photo-2021-02-15-18-01-17.jpg)

2.4.1.1 Модифицируйте класс `MSELoss` из __2.3.1__, реализовав расчет производной относительно предыдущего слоя с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами
 

In [ ]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return torch.mean(torch.pow(y_true - y_pred, 2)) # <реализовать логику MSE>

  def backward(self, y_pred, y_true):
    self.dinput = torch.mean(-2.0*(y_true - y_pred)).repeat(y_pred.shape[0])

2.4.2.2. Модифицируйте класс `Neuron` из __2.4.1.2__:

  1) Реализуйте метод `forward` таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. 

  2) Реализуйте расчет градиента относительно весов `weights` и `bias` с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами

In [ ]:
class Neuron:
  def __init__(self, n_inputs):
    # <создать атрибуты объекта weights и bias>
    self.weights = torch.nn.parameter.Parameter(torch.normal(0, 1, (n_inputs, )))
    self.bias = torch.nn.parameter.Parameter(torch.normal(0, 1, (n_inputs, )))
  
  def forward(self, inputs):
    self.inputs = inputs
    return torch.matmul(inputs, self.weights) + self.bias # <реализовать логику нейрона>
  
  def backward(self, dvalue):
    # dvalue - значение производной, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет значение df/dc (созданное методом backwards у объекта MSELoss)
    self.dweights = torch.matmul(self.inputs.T, dvalue) # df/dW
    self.dbias = torch.sum(dvalue, axis=0, keepdims=True) # df/dB

2.4.2.3 Допишите цикл для настройки весов нейрона

In [ ]:
from sklearn.datasets import make_regression
import numpy as np

n_batch = 5
X, y, coef = make_regression(n_samples=10000, n_features=4, n_informative=4, coef=True, bias=0.5)
X = np.array_split(X, X.shape[0]//n_batch)
y = np.array_split(y, y.shape[0]//n_batch)
X = torch.tensor(X).type(torch.float32) # <преобразуйте массивы numpy в тензоры torch с типом torch.float32
y = torch.tensor(y).type(torch.float32) # <преобразуйте массивы numpy в тензоры torch с типом torch.float32

In [ ]:
n_inputs = X.shape[-1] # <размерность элемента выборки>
learning_rate = 0.1 # скорость обучения
n_epoch = 100 # количество эпох

layer = Neuron(n_inputs)
loss_fn = MSELoss()

losses = []
for epoch in range(n_epoch):
  for x_batch, y_batch in zip(X, y):
    for x, y in zip(x_batch, y_batch.reshape(-1, 1)):
      # forward pass
      y_pred = layer.forward(x) # <прогон через нейрон>
      loss = loss_fn.forward(y_pred, y) / y_pred.shape[-1] # <прогон через функцию потерь>
      losses.append(loss)

      # backprop
      # <вызов методов backward>
      # обратите внимание на последовательность вызовов: от конца к началу
      loss_fn.backward(y_pred, y)
      layer.backward(loss_fn.dinput)

      # <шаг оптимизации для весов (weights и bias) нейрона>
    layer.weights = layer.weights - learning_rate * layer.dweights
    layer.bias = layer.bias - learning_rate * layer.dbias
  if epoch % 10 == 0:
    print('epoch:', epoch, 'loss:', loss.item())

epoch: 0 loss: 95.36964416503906
epoch: 10 loss: 0.7747334837913513
epoch: 20 loss: 0.5428787469863892
epoch: 30 loss: 0.5428777933120728
epoch: 40 loss: 0.5428777933120728
epoch: 50 loss: 0.5428777933120728
epoch: 60 loss: 0.5428777933120728
epoch: 70 loss: 0.5428777933120728
epoch: 80 loss: 0.5428777933120728
epoch: 90 loss: 0.5428777933120728


In [ ]:
torch.mean(y_pred).item(), y.item()

(45.67970657348633, 45.679718017578125)

In [ ]:
layer.weights

tensor([18.5240, 19.8228, 19.1412, 19.4263], grad_fn=<SubBackward0>)

In [ ]:
layer.bias

tensor([82.4676, 83.7430, 84.5828, 80.6727], grad_fn=<SubBackward0>)

2.4.3  Используя один полносвязный слой и  пакетный градиетный спуск, решите задачу регрессии из __2.4.1__

2.4.3.1 Модифицируйте класс `Linear` из __2.1.4__. ([вычисление градиентов](https://i.ibb.co/kgVR6m6/photo-2021-02-15-21-30-28.jpg))

In [ ]:
class Linear:
  def __init__(self, n_features, n_neurons):
    # <создать атрибуты объекта weights и biases>
    self.n_features = n_features
    self.n_neurons = n_neurons
    self.weights = torch.nn.parameter.Parameter(torch.normal(0, 1, (n_features, n_neurons)))
    self.bias = torch.nn.parameter.Parameter(torch.normal(0, 1, (n_neurons, )))
  
  def forward(self, inputs):
    self.inputs = inputs
    return torch.matmul(inputs, self.weights) + self.bias # <реализовать логику слоя>

  def backward(self, dvalue):
    self.dweights = torch.matmul(self.inputs.T, dvalue) # df/dW
    self.dbias = torch.sum(dvalue, axis=0, keepdims=True) # df/dB
    self.dinput = torch.matmul(dvalue, self.weights.T) # df/wX

2.4.3.2 Создайте слой с одним нейроном. Используя класс MSELoss из 2.4.2, убедитесь, что модель обучается

2.4.4 Используя наработки из 2.4, создайте нейросеть и решите задачу регрессии.

Предлагаемая архитектура: 
1. Полносвязный слой с 10 нейронами
2. Активация ReLU
3. Полносвязный слой с 1 нейроном